wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: huggingface
    huggingface_version: 4.11.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1662358129
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 1
      - 13
      4: 3.8.13
      5: 0.12.19
      6: 4.11.0
      8:
      - 5
